// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClY0jEigoGZShFOLBDM7C85MaHhI6cwTE',
    appId: '1:521876673392:android:17654014b6fc3552f575b5',
    messagingSenderId: '521876673392',
    projectId: 'dreamary-7a581',
    storageBucket: 'dreamary-7a581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOELvbZ_jD6nf7H7sW9GCjToot-t0fwgo',
    appId: '1:521876673392:ios:2114b06aeddd5555f575b5',
    messagingSenderId: '521876673392',
    projectId: 'dreamary-7a581',
    storageBucket: 'dreamary-7a581.firebasestorage.app',
    androidClientId: '521876673392-975keqen3nffdkuugps7ejvdej65v5i8.apps.googleusercontent.com',
    iosClientId: '521876673392-m5i713ldr2nfubpkrdvgccmoem888ngd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamaryFlutter',
  );

}